services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dealer
    command: python -m ssmart.run
    ports:
      - "8000:8000"
    volumes:
      - ./data:/ssmart/data
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=ssmart_dealer
      - DB_USER=postgres
      - DB_PASS=52949235
    depends_on:
      - database
    env_file:
      - .env

  database:
    image: postgres:14.6-alpine
    restart: always
    environment:
      - POSTGRES_DB=ssmart_dealer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=52949235
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
